
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Always use the direct Supabase URL - no proxy needed
const SUPABASE_URL = 'https://wmgdwcfliwivqgaqifhw.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZ2R3Y2ZsaXdpdnFnYXFpZmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODMzNzEsImV4cCI6MjA1OTE1OTM3MX0.95E5bST2kWIlihDlM0H8zeD6Dyuv84v-f636TbOuqQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'x-my-custom-header': 'my-app-name',
    },
  },
});
